export const sliderItems = [
    {
      id: 1,
      img: "https://i.ibb.co/XsdmR2c/1.png",
      title: "SUMMER SALE",
      desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
      bg: "f5fafd",
    },
    {
      id: 2,
      img: "https://i.ibb.co/DG69bQ4/2.png",
      title: "AUTUMN COLLECTION",
      desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
      bg: "fcf1ed",
    },
    {
      id: 3,
      img: "https://i.ibb.co/cXFnLLV/3.png",
      title: "LOUNGEWEAR LOVE",
      desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
      bg: "fbf0f4",
    },
  ];

  export const categories = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      title: "SHIRT STYLE!",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      title: "LOUNGEWEAR LOVE",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      title: "LIGHT JACKETS",
    },
  ];

  export const products = [
    {
        id: 1,
        name: "Product 1",
        description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        regularPrice: "$16",
        price: "$15.00",
        image: "https://picsum.photos/600/400?random=1",
        rating: "5",
        reviews: "27485",
        availability: "true",
        category: "cat1",
      },
    {
      id: 2,
      name: "Product 2",
      description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      regularPrice: "$16",
      price: "$1599.00",
      image:  "https://picsum.photos/600/400?random=2",
      rating: "3.5",
      reviews: "27485",
      availability: "true",
    category: "cat1",
    },
    {
        id: 3,
        name: "Product 3",
        description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        regularPrice: "$16",
        price: "$15.00",
        image:  "https://picsum.photos/600/400?random=3",
        rating: "2",
        reviews: "27485",
        availability: "true",
        category: "cat1",
      },
     
      {
        id: 4,
        name: "Product 4",
        description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        regularPrice: "$16",
        price: "$15.00",
        image:  "https://picsum.photos/600/400?random=4",
        rating: "1",
        reviews: "27485",
        availability: "true",
        category: "cat1",
      },
      {
        id: 5,
        name: "Product 5",
        description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        regularPrice: "$16",
        price: "$15.00",
        image:  "https://picsum.photos/600/400?random=5",
        rating: "5",
        reviews: "27485",
        availability: "true",
        category: "cat2",
      },
      {
        id: 6,
        name: "Product 6",
        description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        regularPrice: "$16",
        price: "$15.00",
        image:  "https://picsum.photos/600/400?random=6",
        rating: "3",
        reviews: "27485",
        availability: "true",
        category: "cat2",
      },
      {
        id: 7,
        name: "Product 7",
        description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        regularPrice: "$16",
        price: "$15.00",
        image:  "https://picsum.photos/600/400?random=7",
        rating: "3",
        reviews: "27485",
        availability: "true",
        category: "cat2",
      },
      {
        id: 8,
        name: "Product 8",
        description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        regularPrice: "$16",
        price: "$15.00",
        image: "https://picsum.photos/600/400?random=8",
        rating: "3",
        reviews: "27485",
        availability: "true",
        category: "cat3",
      },
      {
        id: 9,
        name: "Product 9",
        description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        regularPrice: "$16",
        price: "$15.00",
        image:  "https://picsum.photos/600/400?random=9",
        rating: "3",
        reviews: "27485",
        availability: "true",
        category: "cat3",
      },
      {
        id: 10,
        name: "Product 10",
        description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        regularPrice: "$16",
        price: "$15.00",
        image:  "https://picsum.photos/600/400?random=10",
        rating: "3",
        reviews: "27485",
        availability: "true",
        category: "cat3",
      }         
  ];
